blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/jinto-ag/ts-nx-preset/discussions/new?category=q-a
    about: Ask questions and discuss with other community members
  - name: Nx Documentation
    url: https://nx.dev/
    about: Check the Nx documentation for answers to common questions
